### ISSUE TITLE
Where can I find the old version commit?

### ISSUE THREAD

**Issue by mqliutie** [quilljs/parchment#120]
I have clone this repository but it only has one tag named `v2.0.0` I want to find the version `1.1.4`. I can not find which commit release this version

**Comment by huangchen1031** [comment]
Maybe this 551c742f2f227105d353c25fee0f96f15fe3cf8e
This commit was committed at 2018-03-12 14:08:40 with message "bump version",  and version `1.1.4` published at 2018-03-12 14:09:56.
