### ISSUE TITLE
Remove Byte Order Mark (BOM) characters from Blot

### ISSUE THREAD

**Issue by asebold** [quilljs/parchment#124]
Any time I create an embed blot, and it's inserted into a quill editor, the contents of the blot are wrapped in a span with BOM characters on both ends of it (`&#xFEFF;`). 

These are invisible characters that cause all kinds of problems for my app, but I can't figure out where they're coming from. 

What is the purpose of including these characters in blots, and is it possible to get rid of them? 

Code generated in browser: 
![Screenshot from 2023-02-20 20-48-51](https://user-images.githubusercontent.com/9828290/220236265-0a75efe8-92fd-4d28-bcaa-eabab049930d.png)

Code I used to create this blot:
```
let EmbedBlot = Quill.import('blots/embed');

class TagSelectBlot extends EmbedBlot {
	static create(){
		let tags = ['tag1','tag2']
		let node = super.create()
		node.setAttribute('data-tags',tags.join(','))
		node.classList.add('dropdown-menu')
		node.setAttribute('contenteditable', false);
		node.innerHTML = `<li class="dropdown-content"><a class="dropdown-item">${
			tags[0]
		}</a></li><li class="dropdown-content"><a class="dropdown-item">${tags[1]}</a></li>`		
		return node
	}

	static value(node){
		let tags = node.getAttribute('data-tags')
		return tags.split(',')
	}
}

TagSelectBlot.blotName = 'tag-select';
TagSelectBlot.tagName = 'ul';
TagSelectBlot.className = 'pf-editor-tag-select'
```

**Comment by luin** [comment]
Hey @asebold 👋 

They are needed to hold the cursor. What particular issues did you encounter? Let's see if there are solutions for that.

**Comment by luin** [comment]
Yeah they are necessary for holding the cursor. Closing. Feel free to reopen if there are any concerns or suggestions.
