### ISSUE TITLE
Possible typo in Registry.query

### ISSUE THREAD

**Issue by gregdetre** [quilljs/parchment#13]
I was reading through the Parchment source code, and this line looked odd:

https://github.com/quilljs/parchment/blob/master/src/registry.ts#L81

Shouldn't that be a test for equality, rather than an assignment? i.e.

`if (match === classes[names[i]]) ...
`

Apologies if I've misunderstood the intent of the code, or if there's some javascript cleverness here I'm missing. Thanks for all your hard work on Quill and Parchment!

**Comment by jhchen** [comment]
It was being too clever thank you for pointing it out.
