### ISSUE TITLE
Discussion: Regarding TypeScript definitions for Parchment

### ISSUE THREAD

**Issue by sumitkm** [quilljs/parchment#15]
I am trying to maintain TypeScript definitions for Quill at the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/quill) repo.

After using it for a while I realized just having the public APIs declared in the documentations doesn't quite complete the definitions. Because as soon as I try to extend using custom Blots and Formats I run into missing type definitions.

While I can continue to build the TypeScript definitions to add all the formats and blots that Quill supports, fact that most of them inherit from Parchement got me thinking. Since Parchment is written in TS, generating definitions for it should be trivial. I tried it and I had to make a few minor changes in the tsconfig and two other classes to be able to generate TS definitions for Parchments. It will need more work to include it as a part of the webpack build process.

Coming to the questions
1. Should I work on a PR (to Parchment) that enables d.ts file generation (and thus direct access to definitions via npm). Unless someone is working on this already, this might take me a few days to sort out. But advantage of this approach would be, the TS file would always be up to date with the code.
2. Should I work on a completely independent d.ts file (like the current Quill definitions) and submit it to DefinitelyTyped independently. That way, the d.ts file is not tied to Parchment releases and repo, but will be playing catchup with every release.

**Comment by jhchen** [comment]
Why does Parchment need a d.ts file when it is in Typescript already?

**Comment by sumitkm** [comment]
Looks like my email response didn't make it through. Pasting the content again

Hi Jason,

When I refer to Quill's release version I don't have Parchment source. To develop using Quill in TS, I use the quill.d.ts. If quill.d.ts were to refer to parchment.d.ts then I get all the APIs defined in parchment as well. 

I could duplicate all the classes/interfaces that Quill (Blots and Formats) implement/inherit from Parchment, in the quill.d.ts itself. That's one way.

Another way, without parchment definitions, I have to keep Parchment TS code along with my dev code.

Advantage of having parchment written in TS is, the d.ts generation is (nearly automatic).

Hope this clarifies.

Cheers.

**Comment by jhchen** [comment]
If it can be nearly automatic in a set it and forget it way, for example to the existing build pipeline, I am happy to merge it. Otherwise I do not want to add an additional step and maintenance burden to every release.

**Comment by maku** [comment]
@jhchen I think it should be rather easy possible to generate the typescript definitions (*.d.ts files) 

1) Produce declarations via "declaration": true in tsconfig.json -> compilerOptions
2) Then you are able to define the entry point of d.ts file in packages.json via a "types" entry (e.g. "types": "./dist/src/parchment.d.ts")

**Comment by jhchen** [comment]
Thanks for the helpful pointer @maku and thank you @sumitkm for the DefinitelyTyped repo definitions.

**Comment by Maximaximum** [comment]
Looks like this still hasn't been implemented, since parchment/dist folder does not contain any .d.ts files
