### ISSUE TITLE
Engine rule in package.json maybe too strict?

### ISSUE THREAD

**Issue by davidascher** [quilljs/parchment#16]
I was checking out `yarn` today (new package manager to replace npm client), and it complained on a project I have that uses Quill, with:

```
$ yarn
yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[...]
[2/4] 🚚  Fetching packages...
error parchment@1.0.1: The engine "node" is incompatible with this module. Expected version "^5.3".
error Found incompatible module
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
lola:~/src/participedia/frontend on master*
```

FYI:
```
$ node --version
v6.4.0
```

Which makes me think that it may make sense to make the engine line in `package.json` be more generous, maybe using `>=` instead of `^`.

I'm no package.json versioning expert though.

**Comment by djyde** [comment]
+1
