### ISSUE TITLE
Global Blot?

### ISSUE THREAD

**Issue by druti** [quilljs/parchment#21]
Is it possible to create a single blot that acts as an inline, block and embed blot?

**Comment by druti** [comment]
I want to avoid creating three separate blots for one attribute set.

**Comment by jhchen** [comment]
What's the use case?

**Comment by druti** [comment]
I'm implementing authorship in Quill.

**Comment by druti** [comment]
I'm not sure how you're thinking of implementing it when the time comes, I haven't had a chance to look at how it was done in v0.2 yet. I'm hooking into the `text-change` event and modifying the deltas with the proper author attributes. This works fine for my backend but Quill can't handle rendering it properly on all levels (inline, block, embed) when it comes back around. I'd rather let Quill take care of adding the attributes with come kind of constant global author format.

**Comment by druti** [comment]
Any thoughts @jhchen ?

**Comment by druti** [comment]
This waaaas a great feature in Quill, and I'd love to help implement it

**Comment by jhchen** [comment]
I appreciate the interest but it will not be a trivial effort and I'm not sure a global blot is in the right track. If you are willing to put in the effort, then familiarize with Parchment and its README and come up with an implementation proposal and chime in on the existing authorship Issues.
