### ISSUE TITLE
empty line composition input problem in: mac(safari[10.1], chrome[59_dev]), win(chrome[59_dev])

### ISSUE THREAD

**Issue by coder2-seekforwings** [quilljs/parchment#26]
please read it all and clearfully:
detail problments: https://github.com/quilljs/quill/issues/896

For an empty line, I found that the method 'domNode.insertBefore(childNode, refNode)' [https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore], for the older webbrowsers, range object will not change, so the 'getNativeRange' method return corrent result. However, it changes for the latest webbrowsers(safari[10.1], chrome[59_dev]), and in result 'getNativeRange' return wrong result.

I think that the source code hasn't checked whether the parentNode already contains the childNode. And I tried to do so in my forked branch, than the problem fixed. But I want to make sure if it is proper to do so? If it is, i will try to merge to the original master branch.

I will be appreciate if you can answer the question. Let's make it good! @jhchen

**Comment by jhchen** [comment]
Can you submit a Pull Request with your changes and I will take a look?
