### ISSUE TITLE
Lack of code documentation?

### ISSUE THREAD

**Issue by DawidLoubser** [quilljs/parchment#32]
I think that this project's code is quite beautiful and elegant (for example, [Blot](https://github.com/quilljs/parchment/blob/master/src/blot/abstract/blot.ts) ). I find it striking, however, that there is no in-code documentation that describes the API.

*I'm just busy learning Parchment, and good documentation in your code would have really helped me understand the intent behind many of the methods.*

**Comment by jhchen** [comment]
Documentation for *what* the API interface is in the README. As far as *why* they were designed that way, that is a much more complex topic and one that may still be extended as more people experiment with more advanced customizations.

**Comment by DawidLoubser** [comment]
Exactly - the *why* is quite complex, so if the engineer who wrote the interfaces had documented his current thoughts about what the methods in there achieve, it would foster understanding and collaboration.

As it stands, I have no way to discover the "why" - which probably slows down my experimentation.

Thanks for your reply in anyway - but I still feel the same; that this project would benefit from some documentation explaining the thoughts behind the interfaces.

Parchment may turn out to be quite profound in the future, so documentation that reflects that would be fitting. Thanks for a great project.
