### ISSUE TITLE
Allow svg tag.

### ISSUE THREAD

**Issue by bonk** [quilljs/parchment#36]
I want to allow SVG tags in the Quill editor. However, I do not know why, but it will not work. Should it be possible?

**Comment by benbro** [comment]
Quill is a rich text editor, not an HTML editor.What does it mean to add SVG tag in a text editor?

**Comment by bonk** [comment]
Excuse me.  Certainly, in normal usage, addition is not important.  I will close this issue.

After knowing it is not important, in a method using Parchment described in the document,
I tried to expand it so that I could use the SVG tag, but it did not work.
