### ISSUE TITLE
ScrollBlot.optimize() has invalid type

### ISSUE THREAD

**Issue by moward** [quilljs/parchment#37]
`ScrollBlot` extends `ContainerBlot` and its optimize method has type:
```ts
ScrollBlot.optimize(mutations: MutationRecord[] = [], context: {[key: string]: any} = {}): void
```

`ContainerBlot`'s `optimize` has type:
```ts
ContainerBlot.optimize(context: {[key: string]: any})
```

Because of the order of the parameters, the first is not a supertype of the second as it should be.

**Comment by jhchen** [comment]
Is this causing issues and if so what? The desire is to overload this function for ScrollBlot's needs for an array of mutations and ScrollBlot only pass context as the only parameter when it calls its superclass's optimize. The Typescript does not complain so I'm not seeing why it would be invalid.

**Comment by moward** [comment]
The TypeScript compiler error only appears for me with the option `strictNullChecks` turned on. Since neither JS nor TS support method overloading, overridden methods need to be typeable as the superclass method type.

I think a simple fix would be switching the order of the arguments on ScrollBlot's optimize. I imagine this might break any consumers of ScrollBlot though.

**Comment by jhchen** [comment]
A lot of other errors appear if strictNullChecks is turned on. Switching the order also does not get rid of the error as ContainerBlot's signature is only one parameter and ScrollBlot is two. I'm not seeing the practical benefits of this issue. Can you clarify what you are trying to do and how this is getting in the way?

**Comment by crysehillmes** [comment]
There is an answer in [TypeScript function overloading](https://stackoverflow.com/a/24222144):

> You can declare an overloaded function by declaring the function as having a type which has multiple invocation signatures

So, this might work:

```
optimize: {
  (context: { [key: string]: any }): void;
  (mutations: MutationRecord[], context: { [key: string]: any }): void;
};
```
