### ISSUE TITLE
Reference quill editor from blot

### ISSUE THREAD

**Issue by aRusenov** [quilljs/parchment#38]
Hello,

After a lot of searching I couldn't find an example of referencing the editor from a custom blot. The examples I saw tackle this by working with a global quill instance, e.g.:
`var quill = ....`
Is it possible to access the current quill instance where the blot is inserted and if not - is it difficult to implement?

Much appreciated for the great library!

**Comment by jhchen** [comment]
Parchment is the underlaying data model for rich text editors, not just Quill. But sounds like the question is not Quill specific either. Please post you question on StackOverflow and tag with [quill](http://stackoverflow.com/questions/tagged/quill). I will suggest you provide more details about your question though too.

**Comment by reothues** [comment]
where is the stackoverflow reference?
