### ISSUE TITLE
Limit top node of the document to be a table>tbody and only allow children to be tr>td

### ISSUE THREAD

**Issue by viktor-evdokimov** [quilljs/parchment#39]
Hello,
I am trying to figure out how to force ScrollBlot to be a table>tbody and only allow first level children to be Blots represented by `tr` and `td` tag ( e.g. smallest block level Blot is single cell table row).

I understand I need to define my block blot with tag `tr` and override some methods on the blot class.
How do I approach ScrollBlot ?

**Comment by jhchen** [comment]
What have you tried so far?

**Comment by viktor-evdokimov** [comment]
I have block blot for tr defined, and that's it right now.

**Comment by jhchen** [comment]
Okay then try out the `allowedChildren` option and see how far that takes you for your use case.
