### ISSUE TITLE
Type 'undefined' is not assignable to type 'T'.

### ISSUE THREAD

**Issue by juanparadox** [quilljs/parchment#42]
The error is coming from here:
node_modules/parchment/src/collection/linked-list.ts(9,5)

Any thoughts on why this issue is present? Is it simply a type problem?

**Comment by danielmhair** [comment]
I'm getting this also when I installed `ngx-quill`, which installs `quill` and `@types/quill`. It only happens when my `tsconfig.json` file has `strict: true`. Setting it to `strict: false` fixes this. However, I'm going to do a pull request to fix this.

**Comment by danielmhair** [comment]
Actually, looking at it, there will need to have a lot more changes to get it to work right (if statements and others). Does anyone have other ideas on the best way to fix this without changing `strict` to `false`?

**Comment by danielmhair** [comment]
Here is the pull request: https://github.com/quilljs/parchment/pull/43

**Comment by juanparadox** [comment]
@danielmhair I was going through the same thing and was about to submit a PR as well, seems it is important to allow developers using `strict: true` to use the types free of error. Beat me to it!

**Comment by danielmhair** [comment]
Sounds great @juanparadox! To fix it, I set `strict: true` initially, and there are a ton more errors that come up from, but since this was the only error that comes up on my end, I felt no need to do more of it. I have tested these changes in my project and it does seem to fix the build errors.

**Comment by juanparadox** [comment]
@danielmhair Same boat as you, only error present.

**Comment by danielmhair** [comment]
Hey @jhchen, after you merged master, I tried updating my version of `parchment`, but it seems to not receive the updates. The version that it installs is `1.1.3`. I saw that master has the same version number. Have the changes not been published yet?

**Comment by juanparadox** [comment]
@danielmhair seeing the same issue as you.

**Comment by jhchen** [comment]
No it's not pushed. There's some more diligence I need to do before publishing so I'll try to get to that this weekend. FYI for any project that uses version numbers you can look in the commit log and check if the change you are looking for is before or after the version bump.
