### ISSUE TITLE
Add comments to source code and ensure they get inserted in the generated d.ts files

### ISSUE THREAD

**Issue by charrondev** [quilljs/parchment#46]
It would be helpful if the more of the functions in this library had comments. It would be even more helpful if the comments were inserted into the generated d.ts files.

I'm trying to gain a better understanding of parchment so I'm willing to a most of the work in this documentation. Expect a PR shortly.

**Comment by jhchen** [comment]
It would be more helpful if you start with a guide or blog post about how Parchment works or whatever you learn. Code comments are highly subjective so will not be the path of least resistance.
