### ISSUE TITLE
Has no exported member 'Parchment'

### ISSUE THREAD

**Issue by Corsseir** [quilljs/parchment#48]
node_modules/parchment/dist/src/parchment has no exported member 'Parchment'.

1.6.0

**Comment by Charrondev** [comment]
So `parchment/dist/src/parchment.d.ts`is a type definition and doesn't export anything to javascript. You likely want to just import from `parchment` which will resolve to `parchment/dist/parchment.js`.

**Comment by dejan9393** [comment]
It seems that Quill does not currently work correctly with native `esm` imports as a few of its dependencies (`parchment`, `quill-delta`, possibly others) are distributed in `umd` format, which doesn't quite yet support module imports

**Comment by dejan9393** [comment]
It seems that Quill does not currently work correctly with native esm imports as a few of its dependencies (parchment, quill-delta, possibly others) are distributed in umd format, which doesn't quite yet support module imports
