### ISSUE TITLE
Expand documentation

### ISSUE THREAD

**Issue by charrondev** [quilljs/parchment#50]
Now that I've implemented some Custom blots for our companies project, I'm planning to document some of the things I've learned for future maintainers of our project. I'd prefer for that documentation to be public and not in our internal documentation. Some of the topics include:

- [x] Parchment/Quill's document model.
  - The way Blot's connect to each other (LinkedList with prev, next, children, parent).
  - The way Blot's connect their domNode (`blot.domNode` and `domNode.__blot`).
- [x] A Blot's lifecycle
  - `static create() -> constructor() -> attach()`
  - `update()`
  - `optimize()`
  - `remove() -> detach()`
- [x] Different methods of creating a Blot and inserting it somewhere
  - insertAt()/insertBefore()/insertInto()
  - replace()/replaceWith()
- [x] How Blot's are created from DOM Nodes / Requirement to not have overlap between tags or use another method to distinguish DOM Nodes.
- split() / isolate()
- Scopes
  - What are they
  - Why do the exist
  - Hierachy?
- Mapping of DOM Node types to Blots
  - div (wrapper) -> Container
  - TextNode -> TextBlot
  - Span (Container of multiple Text Nodes) -> Inline
  - Paragraph -> Block
- Embed as an escape hatch / Non-contenteditable content.

@jhchen I'd mainly like to know where you would prefer this information to live? Would a docs folder at the top level of the repo do? I'd write it all as markdown, so it would be easy enough to pull pieces out and into the quill documentation if you'd like things to live there eventually.

**Comment by derekaug** [comment]
This would be super helpful for me, as I'm just getting started and some of these more advanced things are not touched at all in the documentation and the code itself is mostly void of documentation.

**Comment by Charrondev** [comment]
I can't claim this is all accurate, but I've got my own fork here with a bunch of comments on the code. I'm probably going to trim some of them down, now that I have a bit better of an understanding, but you can take a look here: https://github.com/vanilla/parchment

**Comment by jhchen** [comment]
As I mentioned in #46 I think it is most helpful if you start with a guide or blog post. If there are elements that I feel is helpful to Quill/Parchment we will go from there. Code comments are highly subjective and I will not debate the topic in Github.

**Comment by Charrondev** [comment]
I'm happy to ignore the code comments and keep them for my own personal knowledge of the project. I've created my first of a series of blog posts on parchment and posted it here:

https://dev.to/charrondev/getting-to-know-quilljs---part-1-parchment-blots-and-lifecycle--3e76

I'd appreciate any feedback you have.

**Comment by Charrondev** [comment]
I'm thinking it would be a bit of an easier read of it could be broken up into sections and cross-linked (and not need the long introductory "What is Quill and why am I writing this article" part at the top.)

**Comment by coxandrew** [comment]
Just wanted to say that this effort is much appreciated, @charrondev! Just reading through your branch with the function comments helped me through the custom blot I'm working on for my project.

**Comment by jacwright** [comment]
@jhchen are you interested in putting parchment docs into the quilljs repo, or this one? I think there is much value to this and would like to know what you would like to see happen.

**Comment by charrondev** [comment]
I have feeling the Quill repo might be the right place. Most of the core blots are extended in a significant way from Quill. I would likely not find myself building on Parchment's Embed directly. I'd much rather build off of Quill's BlockEmbed or Embed.

**Comment by andrei-cacio** [comment]
@charrondev what's the difference betwee Quill's Emebed and Parchmnet's Embed?

**Comment by charrondev** [comment]
There's actually 3 "embed" blots:

- Parchment's `EmbedBlot`
  - Don't use this one.
- Quill's `Embed`
  - This is an "inline" embed. It's contents are padded by invisible whitespace characters that are used to detect modification of the contents and allow you to react. [Here's an example of our mention embed blot](https://github.com/vanilla/vanilla/blob/master/plugins/rich-editor/src/scripts/quill/blots/embeds/MentionBlot.ts).
- Quill's `BlockEmbed`
  - This is for embeds that are like a line of their own.
  - On top of the base parchment blot it supports attributors and descendant children, and has some special handling in quill.
  - [Here's an example of our error blot](https://github.com/vanilla/vanilla/blob/master/plugins/rich-editor/src/scripts/quill/blots/embeds/ErrorBlot.tsx).
