### ISSUE TITLE
Type definitions could be cleaner if the Blot and BlotConstructor interface were removed

### ISSUE THREAD

**Issue by charrondev** [quilljs/parchment#53]
I've been trying to improve the type definitions for Quill and have been running into this issue lately. There are quite a few places where something is typed as being `Blot` (from the interface) or `BlotConstructor` (an interface with `new(): Blot`). The largest issue with the Blot/BlotConstructor interface is that it requires defining static and instance properties/methods in different places. Instead you should be able to use the base Blot class `ShadowBlot` as a class, and where you need its constructor use `typeof ShadowBlot`.

**Comment by jhchen** [comment]
I believe `typeof ShadowBlot` will return 'function', which is not the same.

**Comment by charrondev** [comment]
So typeof ShadowBlot is essentially the constructor function, but it will also have any statically declared properties present. If you take a look at the PR I submitted you'll see that it ends up working quite well.

If you look through the [Advanced section of the typescript handbook](https://www.typescriptlang.org/docs/handbook/classes.html) classes can be used as interfaces. `typeof SomeClass` is also an interface with a `new(): SomeClass` declaration and all static properties of the class.

**Comment by jhchen** [comment]
The current implementation follows the example in  https://www.typescriptlang.org/docs/handbook/interfaces.html#difference-between-the-static-and-instance-sides-of-classes. You are right typeof ShadowBlot does more than the Javascript typeof so I'll take a look at removing BlotConstructor.
