### ISSUE TITLE
create a custom attributor before the initialization of Quill would cause a TypeError:  TypeError: Cannot read property 'getContents' of undefined

### ISSUE THREAD

**Issue by superhobbit** [quilljs/parchment#57]
I'm testing the custom attributor, I created a style attributor: 
```
let CustomStyle = new Parchment.Attributor.Attribute('style', 'style');
Parchment.register(CustomStyle);
```
after this I initialized a new Quill
```
var quill = new Quill('#editor', options);
```
This would cause a TypeError, the stack call is:
```
    at History.record (quill.js:6528)
    at Emitter.<anonymous> (quill.js:6487)
    at Emitter.emit (quill.js:8605)
    at Emitter.emit (quill.js:1895)
    at Quill.modify (quill.js:1626)
    at Quill.setContents (quill.js:1457)
    at new Quill (quill.js:1129)
```
I couldn't figure out why this happened and when I move the customStyle after the initialize of Quill, the error doesn't appear anymore.

However the error didn't appear either when I tried to implement the style attributors before the initialize of Quill
```
let colors = new Parchment.Attributor.Style('background-color', 'background-color');
Parchment.register(colors);
...
var quill = new Quill('#editor', options);
```

I know I supposed to implement the style attributor when I'm trying to apply certain style to the domNode, I just couldn't figure out why create the custom attributor before the initialization of Quill would cause such an error.

Any enlightenment would be really appreciated!!

**Comment by pengliheng** [comment]
same issue
