### ISSUE TITLE
Class Attributors variations cannot contain hyphens

### ISSUE THREAD

**Issue by marciodsousa** [quilljs/parchment#69]
Hi,

Just recently noticed that Class Attributors variations cannot contain hyphens and if they do Parchment is not able to find the proper blot to process.

So I would suggest to add this info into the documentation regarding the expected pattern for the end classes:
`[class-attributor-name]` `[-]` `[variation_name_without_any_hyphens]`

Using quill-color as an example, if i define a color with a class called "light-brown":
`[ql-color]` `[-]` `[light-brown]`

Class Attributor would actually end up looking for the attributor with the keyName `ql-color-light` which normally wouldn't exist.

Another suggestion would be to use/expect another character to separate the keyName from the variation less common than `-` but that would probably break functionality for **a lot** of people.

Please let me know if there's any other info I'd need to provide.

**Comment by pirsquare** [comment]
Here's the code causing this issue

```
const text = "ql-color-light-brown";
const output = text.split(/\s+/).map(function(name) {
      return name
        .split('-')
        .slice(0, -1)
        .join('-');
    });
 };
console.log(text); // ql-color-light
```

See [Reference Line](https://github.com/quilljs/parchment/blob/067c392fe1e6f9b2c480bf4cc00a2e10a72e5ef1/src/attributor/class.ts#L12)

**Comment by pirsquare** [comment]
Looks like the approach to avoid this issue is to stick to underscores. 
`ql-color-light_brown` instead of `ql-color-light-brown`

See [reference line](https://github.com/quilljs/parchment/blob/067c392fe1e6f9b2c480bf4cc00a2e10a72e5ef1/src/attributor/class.ts#L12) for this issue.
