### ISSUE TITLE
TypeScript declarations no longer produced in 2.0

### ISSUE THREAD

**Issue by alecgibson** [quilljs/parchment#84]
TypeScript declarations were disabled in this 2.0 commit: https://github.com/quilljs/parchment/commit/42ad4244110b9c872a3e8defb316f17fd64bc294

What was the reason for that? We have TypeScript classes that extend from Parchment classes, and it would be nice to have the TS definitions available, please!

**Comment by alecgibson** [comment]
Aha fixed with a `tsconfig.json` update:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "parchment": ["node_modules/parchment/src/parchment"]
    }
  }
}
```

**Comment by alecgibson** [comment]
I'm running into this issue again, because I'd like to use the new [`override`](https://www.typescriptlang.org/tsconfig#noImplicitOverride) keyword, but I can't because we compile `parchment` from TypeScript (which then throws compiler warnings).

It's pretty weird for us to be compiling a 3rd-party library, so it would be nice to just require the compiled JS, and be able to use a type definition.

Why was the type definition removed?

**Comment by luin** [comment]
Hey @alecgibson 👋 ,

Sorry for the late reply! Declarations are included in the latest Parchment version so closing this. Feel free to reopen if there are any other issues.
