### ISSUE TITLE
Is this condition of `uiNode` a typo?

### ISSUE THREAD

**Issue by bflatmajor** [quilljs/parchment#98]
https://github.com/quilljs/parchment/blob/569bc9e37bf0a4201bf5bba8cffeea7b38b59862/src/blot/abstract/parent.ts#L364

I guess the `uiNode` should be ignored with ` node.parentNode === this.domNode && node !== this.uiNode`?

**Comment by luin** [comment]
Hey @bflatmajor 👋 ,

Thanks for raising this! I've confirmed it's a bug. Created a fix: https://github.com/quilljs/parchment/pull/116.

**Comment by bflatmajor** [comment]
骅骅诈尸
